include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.config.dart'
    - '**/generated/**'
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_relative_imports: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    require_trailing_commas: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_const: true
    unnecessary_new: true
