targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
      json_serializable:
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
      riverpod_generator:
        generate_for:
          - lib/**/*.dart
      injectable_generator:injectable_builder:
        enabled: false
      injectable_generator:injectable_config_builder:
        enabled: false
