import '../models/clothing_item.dart';
import '../models/outfit_entry.dart';

/// 提供默认穿搭和衣橱数据，首次启动时自动填充。
class DefaultDataService {
  /// 生成 10 条默认穿搭记录，图片来自 assets/cp/cp1~cp10.jpg
  static List<OutfitEntry> generateDefaultOutfits() {
    final now = DateTime.now();
    return [
      OutfitEntry(
        id: 'default_outfit_1',
        imagePath: 'assets/cp/cp1.jpg',
        title: '春日通勤·卡其风衣',
        date: now.subtract(const Duration(days: 1)),
        occasion: '通勤',
        mood: '干练',
        notes: '微凉的早晨，卡其色风衣搭配白色衬衫和直筒西裤，简单却很有精神。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_2',
        imagePath: 'assets/cp/cp2.jpg',
        title: '周末咖啡·慵懒针织',
        date: now.subtract(const Duration(days: 3)),
        occasion: '休闲',
        mood: '放松',
        notes: '宽松的奶白色针织衫配牛仔裤，手里一杯拿铁，享受慢节奏的周末。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_3',
        imagePath: 'assets/cp/cp3.jpg',
        title: '约会之夜·小黑裙',
        date: now.subtract(const Duration(days: 5)),
        occasion: '约会',
        mood: '心动',
        notes: '经典小黑裙搭配金色耳饰，淡淡的香水，刚刚好的温柔。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_4',
        imagePath: 'assets/cp/cp4.jpg',
        title: '晨跑公园·运动套装',
        date: now.subtract(const Duration(days: 7)),
        occasion: '运动',
        mood: '活力',
        notes: '清晨六点的公园，轻便的运动背心搭配速干裤，跑起来风都是甜的。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_5',
        imagePath: 'assets/cp/cp5.jpg',
        title: '旅途时光·舒适百搭',
        date: now.subtract(const Duration(days: 10)),
        occasion: '旅行',
        mood: '自在',
        notes: '亚麻衬衫加阔腿裤，背一个帆布包，走在陌生的街道上也很安心。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_6',
        imagePath: 'assets/cp/cp6.jpg',
        title: '会议日·极简西装',
        date: now.subtract(const Duration(days: 12)),
        occasion: '通勤',
        mood: '专注',
        notes: '深灰色西装外套配白T，少即是多，自信从穿着开始。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_7',
        imagePath: 'assets/cp/cp7.jpg',
        title: '下午茶·碎花半裙',
        date: now.subtract(const Duration(days: 15)),
        occasion: '休闲',
        mood: '愉悦',
        notes: '浅色碎花半裙搭配简约上衣，和好友聊了整个下午。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_8',
        imagePath: 'assets/cp/cp8.jpg',
        title: '海边漫步·清爽亚麻',
        date: now.subtract(const Duration(days: 18)),
        occasion: '旅行',
        mood: '宁静',
        notes: '白色亚麻衬衫被海风吹得鼓起来，脚下的沙子还带着温度。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_9',
        imagePath: 'assets/cp/cp9.jpg',
        title: '瑜伽晨练·舒适运动',
        date: now.subtract(const Duration(days: 20)),
        occasion: '运动',
        mood: '平和',
        notes: '柔软的运动套装，在晨光中完成每一组动作，身心都被唤醒。',
        clothingItemIds: const [],
      ),
      OutfitEntry(
        id: 'default_outfit_10',
        imagePath: 'assets/cp/cp10.jpg',
        title: '纪念日·精心打扮',
        date: now.subtract(const Duration(days: 25)),
        occasion: '约会',
        mood: '幸福',
        notes: '特意选了最喜欢的衬衫和半裙，有些日子值得被认真对待。',
        clothingItemIds: const [],
      ),
    ];
  }

  /// 生成默认衣橱单品（与默认穿搭对应）
  static List<ClothingItem> generateDefaultClothingItems() {
    final now = DateTime.now();
    return [
      ClothingItem(
        id: 'default_item_1',
        imagePath: 'assets/cp/cp1.jpg',
        name: '卡其色风衣',
        category: '外套',
        color: '卡其',
        season: '春',
        isPurchased: true,
        careNotes: '干洗为佳，避免暴晒。',
        createdAt: now.subtract(const Duration(days: 60)),
      ),
      ClothingItem(
        id: 'default_item_2',
        imagePath: 'assets/cp/cp2.jpg',
        name: '奶白针织衫',
        category: '上装',
        color: '米白',
        season: '冬',
        isPurchased: true,
        careNotes: '手洗或轻柔机洗，平铺晾干。',
        createdAt: now.subtract(const Duration(days: 50)),
      ),
      ClothingItem(
        id: 'default_item_3',
        imagePath: 'assets/cp/cp3.jpg',
        name: '经典小黑裙',
        category: '裙装',
        color: '黑色',
        season: '四季',
        isPurchased: true,
        careNotes: '低温熨烫，悬挂存放。',
        createdAt: now.subtract(const Duration(days: 45)),
      ),
      ClothingItem(
        id: 'default_item_4',
        imagePath: 'assets/cp/cp4.jpg',
        name: '运动背心套装',
        category: '运动',
        color: '灰色',
        season: '夏',
        isPurchased: true,
        careNotes: '机洗，避免柔顺剂。',
        createdAt: now.subtract(const Duration(days: 40)),
      ),
      ClothingItem(
        id: 'default_item_5',
        imagePath: 'assets/cp/cp5.jpg',
        name: '亚麻衬衫',
        category: '上装',
        color: '白色',
        season: '夏',
        isPurchased: true,
        careNotes: '温水手洗，自然晾干。',
        createdAt: now.subtract(const Duration(days: 35)),
      ),
      ClothingItem(
        id: 'default_item_6',
        imagePath: 'assets/cp/cp6.jpg',
        name: '深灰西装外套',
        category: '外套',
        color: '深灰',
        season: '秋',
        isPurchased: true,
        careNotes: '干洗，使用宽肩衣架。',
        createdAt: now.subtract(const Duration(days: 30)),
      ),
      ClothingItem(
        id: 'default_item_7',
        imagePath: 'assets/cp/cp7.jpg',
        name: '碎花半裙',
        category: '裙装',
        color: '浅粉',
        season: '春',
        isPurchased: true,
        careNotes: '轻柔机洗，低温熨烫。',
        createdAt: now.subtract(const Duration(days: 25)),
      ),
      ClothingItem(
        id: 'default_item_8',
        imagePath: 'assets/cp/cp8.jpg',
        name: '白色亚麻阔腿裤',
        category: '下装',
        color: '白色',
        season: '夏',
        isPurchased: true,
        careNotes: '冷水洗涤，避免拧干。',
        createdAt: now.subtract(const Duration(days: 20)),
      ),
      ClothingItem(
        id: 'default_item_9',
        imagePath: 'assets/cp/cp9.jpg',
        name: '瑜伽运动套装',
        category: '运动',
        color: '莫兰迪绿',
        season: '四季',
        isPurchased: true,
        careNotes: '机洗，勿用漂白剂。',
        createdAt: now.subtract(const Duration(days: 15)),
      ),
      ClothingItem(
        id: 'default_item_10',
        imagePath: 'assets/cp/cp10.jpg',
        name: '真丝衬衫',
        category: '上装',
        color: '雾蓝',
        season: '春',
        isPurchased: true,
        careNotes: '手洗或干洗，低温熨烫。',
        createdAt: now.subtract(const Duration(days: 10)),
      ),
    ];
  }
}
