import 'models/faction.dart';
import 'models/rarity.dart';
import 'models/hero.dart';
import 'models/stage.dart';

/// 英雄画像リソースリスト
const List<String> HERO_IMAGES = [
  'assets/Role/black-hair-medic.jpeg',
  'assets/Role/black-witch-girl.jpeg',
  'assets/Role/blonde-pirate-gunner.jpeg',
  'assets/Role/blonde-sword-knight.jpeg',
  'assets/Role/blonde-valkyrie-warrior.jpeg',
  'assets/Role/blonde-winter-defender.jpeg',
  'assets/Role/blue-hair-explorer.jpeg',
  'assets/Role/blue-magic-swordsman.jpeg',
  'assets/Role/blue-naval-captain.jpeg',
  'assets/Role/blue-sword-maiden.jpeg',
  'assets/Role/brown-maid-alchemist.jpeg',
  'assets/Role/cyborg-engineer-man.jpeg',
  'assets/Role/dark-cleric-girl.jpeg',
  'assets/Role/dark-magic-scholar.jpeg',
  'assets/Role/dark-pirate-captain.jpeg',
  'assets/Role/dark-rogue-assassin.jpeg',
  'assets/Role/dark-spear-dragoon.jpeg',
  'assets/Role/dark-spear-warrior.jpeg',
  'assets/Role/dragon-horn-lady.jpeg',
  'assets/Role/dual-axe-barbarian.jpeg',
  'assets/Role/falcon-hunter-man.jpeg',
  'assets/Role/forge-blacksmith-girl.jpeg',
  'assets/Role/goggle-engineer-girl.jpeg',
  'assets/Role/gold-red-knight.jpeg',
  'assets/Role/green-druid-healer.jpeg',
  'assets/Role/green-hood-ranger.jpeg',
  'assets/Role/heavy-hammer-girl.jpeg',
  'assets/Role/ice-crystal-mage.jpeg',
  'assets/Role/library-mage-girl.jpeg',
  'assets/Role/map-reader-adventurer.jpeg',
  'assets/Role/martial-arts-girl.jpeg',
  'assets/Role/mask-bird-tamer.jpeg',
  'assets/Role/potion-alchemist-girl.jpeg',
  'assets/Role/red-demon-lord.jpeg',
  'assets/Role/red-fire-mage.jpeg',
  'assets/Role/royal-blonde-lady.jpeg',
  'assets/Role/silver-rapier-fencer.jpeg',
  'assets/Role/silver-shield-knight.jpeg',
  'assets/Role/silver-wizard-lord.jpeg',
  'assets/Role/snow-merchant-scales.jpeg',
  'assets/Role/star-cape-astronomer.jpeg',
  'assets/Role/tavern-merchant-man.jpeg',
  'assets/Role/time-mage-girl.jpeg',
  'assets/Role/traveling-bard-musician.jpeg',
  'assets/Role/white-blade-dancer.jpeg',
  'assets/Role/white-hair-defender.jpeg',
  'assets/Role/white-robe-cleric.jpeg',
  'assets/Role/white-spirit-elf.jpeg',
  'assets/Role/winter-merchant-scales.jpeg',
  'assets/Role/winter-shield-guard.jpeg',
  'assets/Role/wolf-spear-rider.jpeg',
  'assets/Role/yellow-monk-brawler.jpeg',
];

/// 英雄 ID に基づいて対応する画像パスを取得する
String getHeroImageById(String id, int index) {
  if (id.startsWith('h')) {
    final imgIndex = int.tryParse(id.substring(1)) ?? 1;
    if (imgIndex > 0 && imgIndex <= HERO_IMAGES.length) {
      return HERO_IMAGES[imgIndex - 1];
    }
  }
  // デフォルトでは最初の画像を返す
  return HERO_IMAGES.first;
}

const Map<FactionType, Faction> FACTIONS = {
  FactionType.fire: Faction.FIRE,
  FactionType.water: Faction.WATER,
  FactionType.wind: Faction.WIND,
  FactionType.light: Faction.LIGHT,
  FactionType.dark: Faction.DARK,
};

const Map<RarityType, Rarity> RARITIES = {
  RarityType.UR: Rarity.UR,
  RarityType.SSR: Rarity.SSR,
  RarityType.SR: Rarity.SR,
  RarityType.R: Rarity.R,
};

const List<HeroTemplate> HERO_TEMPLATES = [
  // UR ヒーロー
  HeroTemplate(
    id: 'h1',
    name: 'フレイヤ',
    title: '緋紅の傘蓋',
    rarity: RarityType.UR,
    faction: FactionType.fire,
    heroClass: HeroClass.guardian,
    baseHp: 15000,
    baseAtk: 1200,
    baseDef: 800,
    baseSpd: 100,
    skills: ['陽炎斬撃', '赤狐の庇護傘'],
    image: 'assets/Role/red-fire-mage.jpeg',
  ),
  HeroTemplate(
    id: 'h2',
    name: 'ロティア',
    title: '夢を描く遊星',
    rarity: RarityType.UR,
    faction: FactionType.water,
    heroClass: HeroClass.mage,
    baseHp: 8000,
    baseAtk: 2500,
    baseDef: 400,
    baseSpd: 120,
    skills: ['墨水飛散', '神筆鯨魚'],
    image: 'assets/Role/blue-magic-swordsman.jpeg',
  ),
  HeroTemplate(
    id: 'h3',
    name: '蒼刃',
    title: '疾風の剣影',
    rarity: RarityType.UR,
    faction: FactionType.wind,
    heroClass: HeroClass.assassin,
    baseHp: 9000,
    baseAtk: 1800,
    baseDef: 300,
    baseSpd: 150,
    skills: ['風刃', '絶影瞬獄殺'],
    image: 'assets/Role/green-hood-ranger.jpeg',
  ),
  HeroTemplate(
    id: 'h4',
    name: 'ミカエル',
    title: '聖光の使者',
    rarity: RarityType.UR,
    faction: FactionType.light,
    heroClass: HeroClass.support,
    baseHp: 10000,
    baseAtk: 1500,
    baseDef: 600,
    baseSpd: 110,
    skills: ['聖光普照', '天使の祝福'],
    image: 'assets/Role/white-robe-cleric.jpeg',
  ),
  HeroTemplate(
    id: 'h5',
    name: 'リリス',
    title: '深淵の魔女',
    rarity: RarityType.UR,
    faction: FactionType.dark,
    heroClass: HeroClass.mage,
    baseHp: 7500,
    baseAtk: 2800,
    baseDef: 350,
    baseSpd: 130,
    skills: ['虚空裂変', '深淵の凝視'],
    image: 'assets/Role/black-witch-girl.jpeg',
  ),
  // SSR ヒーロー
  HeroTemplate(
    id: 'h6',
    name: 'レオ',
    title: '黄金の獅子心',
    rarity: RarityType.SSR,
    faction: FactionType.light,
    heroClass: HeroClass.warrior,
    baseHp: 12000,
    baseAtk: 1600,
    baseDef: 900,
    baseSpd: 85,
    skills: ['獅子奮迅', '聖剣揮舞'],
    image: 'assets/Role/gold-red-knight.jpeg',
  ),
  HeroTemplate(
    id: 'h7',
    name: 'エリア',
    title: '氷晶の魔導士',
    rarity: RarityType.SSR,
    faction: FactionType.water,
    heroClass: HeroClass.mage,
    baseHp: 7000,
    baseAtk: 2200,
    baseDef: 380,
    baseSpd: 115,
    skills: ['氷霜新星', '氷寒の盾'],
    image: 'assets/Role/ice-crystal-mage.jpeg',
  ),
  HeroTemplate(
    id: 'h8',
    name: '影',
    title: '暗夜の刺客',
    rarity: RarityType.SSR,
    faction: FactionType.dark,
    heroClass: HeroClass.assassin,
    baseHp: 8500,
    baseAtk: 1900,
    baseDef: 320,
    baseSpd: 155,
    skills: ['影襲', '暗殺技'],
    image: 'assets/Role/dark-rogue-assassin.jpeg',
  ),
  HeroTemplate(
    id: 'h9',
    name: 'エリン',
    title: '森の守護者',
    rarity: RarityType.SSR,
    faction: FactionType.wind,
    heroClass: HeroClass.archer,
    baseHp: 9000,
    baseAtk: 1700,
    baseDef: 450,
    baseSpd: 125,
    skills: ['自然の怒り', '精霊の祝福'],
    image: 'assets/Role/green-druid-healer.jpeg',
  ),
  HeroTemplate(
    id: 'h10',
    name: 'ロラン',
    title: '銀甲の騎士',
    rarity: RarityType.SSR,
    faction: FactionType.light,
    heroClass: HeroClass.guardian,
    baseHp: 14000,
    baseAtk: 1100,
    baseDef: 1000,
    baseSpd: 80,
    skills: ['盾打撃', '聖光の守護'],
    image: 'assets/Role/silver-shield-knight.jpeg',
  ),
  // SR ヒーロー
  HeroTemplate(
    id: 'h11',
    name: 'クロエ',
    title: '薬剤の錬金術師',
    rarity: RarityType.SR,
    faction: FactionType.water,
    heroClass: HeroClass.support,
    baseHp: 6500,
    baseAtk: 1200,
    baseDef: 400,
    baseSpd: 105,
    skills: ['治癒の薬水', '錬金術'],
    image: 'assets/Role/potion-alchemist-girl.jpeg',
  ),
  HeroTemplate(
    id: 'h12',
    name: 'アーサー',
    title: '流浪の剣客',
    rarity: RarityType.SR,
    faction: FactionType.light,
    heroClass: HeroClass.warrior,
    baseHp: 10000,
    baseAtk: 1400,
    baseDef: 700,
    baseSpd: 95,
    skills: ['連斬', '闘志昂揚'],
    image: 'assets/Role/blonde-sword-knight.jpeg',
  ),
  HeroTemplate(
    id: 'h13',
    name: 'エミリー',
    title: 'メイド錬金術師',
    rarity: RarityType.SR,
    faction: FactionType.fire,
    heroClass: HeroClass.support,
    baseHp: 7000,
    baseAtk: 1100,
    baseDef: 450,
    baseSpd: 100,
    skills: ['メイドサービス', '炎の錬金'],
    image: 'assets/Role/brown-maid-alchemist.jpeg',
  ),
  HeroTemplate(
    id: 'h14',
    name: 'リン',
    title: '武道家',
    rarity: RarityType.SR,
    faction: FactionType.wind,
    heroClass: HeroClass.assassin,
    baseHp: 8000,
    baseAtk: 1600,
    baseDef: 350,
    baseSpd: 140,
    skills: ['気功波', '瞬歩'],
    image: 'assets/Role/martial-arts-girl.jpeg',
  ),
  HeroTemplate(
    id: 'h15',
    name: 'エド',
    title: '護目エンジニア',
    rarity: RarityType.SR,
    faction: FactionType.light,
    heroClass: HeroClass.archer,
    baseHp: 7500,
    baseAtk: 1500,
    baseDef: 400,
    baseSpd: 110,
    skills: ['機械改造', 'レーザー射撃'],
    image: 'assets/Role/goggle-engineer-girl.jpeg',
  ),
  // R ヒーロー
  HeroTemplate(
    id: 'h16',
    name: 'ジャック',
    title: '旅館の商人',
    rarity: RarityType.R,
    faction: FactionType.light,
    heroClass: HeroClass.warrior,
    baseHp: 9000,
    baseAtk: 1000,
    baseDef: 600,
    baseSpd: 85,
    skills: ['取引', '商業の才'],
    image: 'assets/Role/tavern-merchant-man.jpeg',
  ),
  HeroTemplate(
    id: 'h17',
    name: '雪',
    title: '氷雪の魔導士',
    rarity: RarityType.R,
    faction: FactionType.water,
    heroClass: HeroClass.mage,
    baseHp: 6000,
    baseAtk: 1300,
    baseDef: 300,
    baseSpd: 100,
    skills: ['氷錐の術', '霜凍新星'],
    image: 'assets/Role/library-mage-girl.jpeg',
  ),
  HeroTemplate(
    id: 'h18',
    name: 'ホーク',
    title: '鷹狩の猎人',
    rarity: RarityType.R,
    faction: FactionType.wind,
    heroClass: HeroClass.archer,
    baseHp: 7000,
    baseAtk: 1200,
    baseDef: 350,
    baseSpd: 115,
    skills: ['鷹撃', '追跡術'],
    image: 'assets/Role/falcon-hunter-man.jpeg',
  ),
  HeroTemplate(
    id: 'h19',
    name: 'ロザ',
    title: '闇の祭司',
    rarity: RarityType.R,
    faction: FactionType.dark,
    heroClass: HeroClass.support,
    baseHp: 6500,
    baseAtk: 1000,
    baseDef: 400,
    baseSpd: 95,
    skills: ['闇癒', '呪い'],
    image: 'assets/Role/dark-cleric-girl.jpeg',
  ),
  HeroTemplate(
    id: 'h20',
    name: 'ブラック',
    title: '黒髪の医師',
    rarity: RarityType.R,
    faction: FactionType.light,
    heroClass: HeroClass.support,
    baseHp: 6800,
    baseAtk: 900,
    baseDef: 420,
    baseSpd: 98,
    skills: ['治癒術', '解毒'],
    image: 'assets/Role/black-hair-medic.jpeg',
  ),
];

const List<Stage> STAGES = [
  Stage(
    id: 1,
    name: '1-1 スライムの森',
    recLevel: 1,
    bg: 'forest',
    drops: ['EXP', 'Gold'],
    story: [
      {"speaker": "ナレーター", "content": "一界へようこそ。ここがあなたの旅の始まりです。"},
      {"speaker": "スライム", "content": "グルル…！"},
    ],
  ),
  Stage(
    id: 2,
    name: '1-2 ゴブリンキャンプ',
    recLevel: 15,
    bg: 'camp',
    drops: ['Gold'],
    story: [
      {"speaker": "蒼刃", "content": "気をつけろ、前方にゴブリンの斥候がいる。"},
    ],
  ),
  Stage(
    id: 3,
    name: '1-3 遺された聖殿',
    recLevel: 40,
    bg: 'temple',
    drops: ['Gems'],
    story: [
      {"speaker": "ミカエル", "content": "聖殿を侵すことは許さん、ここにある闇を浄化せよ！"},
    ],
  ),
  Stage(
    id: 4,
    name: '1-4 神々の黄昏',
    recLevel: 80,
    bg: 'altar',
    drops: ['UR Shards'],
    story: [
      {"speaker": "深淵統領", "content": "凡人よ、虚無からの恐怖を味わうがいい！"},
    ],
  ),
  // 新規 10 ステージ追加
  Stage(
    id: 5,
    name: '2-1 霜雪の凍土',
    recLevel: 120,
    bg: 'snow',
    drops: ['Blue Ore'],
    story: [
      {"speaker": "ロティア", "content": "ここの画用紙はすべて凍っている、火をつけなければならない。"},
    ],
  ),
  Stage(
    id: 6,
    name: '2-2 溶岩の心臓',
    recLevel: 180,
    bg: 'lava',
    drops: ['Fire Core'],
    story: [
      {"speaker": "フレイヤ", "content": "この温度…まさに紅傘が舞うのに最適な場所だ。"},
    ],
  ),
  Stage(
    id: 7,
    name: '2-3 迷幻の森',
    recLevel: 250,
    bg: 'mist',
    drops: ['Herb'],
    story: [
      {"speaker": "ナレーター", "content": "濃い霧が立ち込め、あなたの感覚は幻覚を見始めている。"},
    ],
  ),
  Stage(
    id: 8,
    name: '2-4 機械の廃都',
    recLevel: 350,
    bg: 'city',
    drops: ['Parts'],
    story: [
      {"speaker": "蒼刃", "content": "金属の匂い、この守衛に魂はない。"},
    ],
  ),
  Stage(
    id: 9,
    name: '2-5 遠古の遺跡',
    recLevel: 500,
    bg: 'ruins',
    drops: ['Relic'],
    story: [
      {"speaker": "ミカエル", "content": "これは神々が残した最後の警告だ。"},
    ],
  ),
  Stage(
    id: 10,
    name: '3-1 極光の頂',
    recLevel: 700,
    bg: 'sky',
    drops: ['Feather'],
    story: [
      {"speaker": "ナレーター", "content": "世界の頂上に立ち、嵐が酝酿している。"},
    ],
  ),
  Stage(
    id: 11,
    name: '3-2 虚無の隙間',
    recLevel: 1000,
    bg: 'void',
    drops: ['Void Soul'],
    story: [
      {"speaker": "リリス", "content": "私の領地へようこそ、小虫ども。"},
    ],
  ),
  Stage(
    id: 12,
    name: '3-3 星の海',
    recLevel: 1500,
    bg: 'space',
    drops: ['Stardust'],
    story: [
      {"speaker": "ナレーター", "content": "この戦いは、銀河の距離を跨越した。"},
    ],
  ),
  Stage(
    id: 13,
    name: '3-4 混沌の源',
    recLevel: 2200,
    bg: 'chaos',
    drops: ['Core'],
    story: [
      {"speaker": "蒼刃", "content": "因果律は崩壊した、血路を切り開くのみだ。"},
    ],
  ),
  Stage(
    id: 14,
    name: '終章：一界の門',
    recLevel: 3500,
    bg: 'gate',
    drops: ['Everything'],
    story: [
      {"speaker": "謎の人物", "content": "旅の終点は、まさに始点なり。"},
    ],
  ),
  // ========== 第四章：深淵回廊 ==========
  Stage(
    id: 15,
    name: '4-1 深淵の入口',
    recLevel: 5000,
    bg: 'void',
    drops: ['Dark Shard'],
    story: [
      {"speaker": "ナレーター", "content": "深遠なる闇が召喚している。勇敢なる冒険者よ、準備はできたか？"},
    ],
  ),
  Stage(
    id: 16,
    name: '4-2 幽闇の洞窟',
    recLevel: 5800,
    bg: 'cave',
    drops: ['Shadow Crystal'],
    story: [
      {"speaker": "影", "content": "ここの闇…私が想像していたよりさらに深い。"},
    ],
  ),
  Stage(
    id: 17,
    name: '4-3 亡霊の要塞',
    recLevel: 6700,
    bg: 'fortress',
    drops: ['Soul Stone'],
    story: [
      {"speaker": "ロザ", "content": "亡霊の哀嚎、私が超度してあげよう。"},
    ],
  ),
  Stage(
    id: 18,
    name: '4-4 呪いの神殿',
    recLevel: 7800,
    bg: 'temple',
    drops: ['Cursed Orb'],
    story: [
      {"speaker": "ミカエル", "content": "聖光よ、この呪われた聖地を浄化せよ！"},
    ],
  ),
  Stage(
    id: 19,
    name: '4-5 深淵の魔竜',
    recLevel: 9000,
    bg: 'altar',
    drops: ['Dragon Heart'],
    story: [
      {"speaker": "深淵魔竜", "content": "渺小なる蟻よ、よくも私の威厳に挑んだな？"},
    ],
  ),
  // ========== 第五章：天空の城 ==========
  Stage(
    id: 20,
    name: '5-1 雲上の庭園',
    recLevel: 10500,
    bg: 'sky',
    drops: ['Cloud Feather'],
    story: [
      {"speaker": "ナレーター", "content": "雲間に漂う神秘的な庭園、まるで仙境のよう。"},
    ],
  ),
  Stage(
    id: 21,
    name: '5-2 風の塔',
    recLevel: 12000,
    bg: 'tower',
    drops: ['Wind Essence'],
    story: [
      {"speaker": "蒼刃", "content": "風の息遣い、私が知っている匂いだ。"},
    ],
  ),
  Stage(
    id: 22,
    name: '5-3 雷霆の聖所',
    recLevel: 14000,
    bg: 'shrine',
    drops: ['Thunder Stone'],
    story: [
      {"speaker": "ロティア", "content": "雷鳴が轟き、絵巻もまた震えよう。"},
    ],
  ),
  Stage(
    id: 23,
    name: '5-4 天使の祭壇',
    recLevel: 16500,
    bg: 'altar',
    drops: ['Angel Tear'],
    story: [
      {"speaker": "ミカエル", "content": "これは…先輩たちがかつて戦った場所だ。"},
    ],
  ),
  Stage(
    id: 24,
    name: '5-5 天空の覇者',
    recLevel: 19000,
    bg: 'sky',
    drops: ['Sky Shard'],
    story: [
      {"speaker": "雷鳥王", "content": "この天空は、私が守護する！"},
    ],
  ),
  // ========== 第六章：海底遺跡 ==========
  Stage(
    id: 25,
    name: '6-1 深海の海峡',
    recLevel: 22000,
    bg: 'ocean',
    drops: ['Pearl'],
    story: [
      {"speaker": "ナレーター", "content": "深遠なる海底、古老なる秘密が隠されている。"},
    ],
  ),
  Stage(
    id: 26,
    name: '6-2 珊瑚の迷宮',
    recLevel: 25000,
    bg: 'maze',
    drops: ['Coral Branch'],
    story: [
      {"speaker": "エリア", "content": "氷と水、ここに交わる。"},
    ],
  ),
  Stage(
    id: 27,
    name: '6-3 沈没船の墓地',
    recLevel: 29000,
    bg: 'shipwreck',
    drops: ['Treasure Map'],
    story: [
      {"speaker": "影", "content": "宝の匂い…そして死もまた。"},
    ],
  ),
  Stage(
    id: 28,
    name: '6-4 海神の殿',
    recLevel: 33000,
    bg: 'palace',
    drops: ['Trident Fragment'],
    story: [
      {"speaker": "ロティア", "content": "この汪洋もまた、私の画布なり！"},
    ],
  ),
  Stage(
    id: 29,
    name: '6-5 リヴァイアサン',
    recLevel: 38000,
    bg: 'ocean',
    drops: ['Leviathan Scale'],
    story: [
      {"speaker": "リヴァイアサン", "content": "深海、それがお前の墓となる！"},
    ],
  ),
  // ========== 第七章：時の塔 ==========
  Stage(
    id: 30,
    name: '7-1 時空の裂け目',
    recLevel: 43000,
    bg: 'void',
    drops: ['Time Dust'],
    story: [
      {"speaker": "ナレーター", "content": "時の長河、ここに扭曲す。"},
    ],
  ),
  Stage(
    id: 31,
    name: '7-2 過去の残響',
    recLevel: 48000,
    bg: 'ruins',
    drops: ['Memory Crystal'],
    story: [
      {"speaker": "謎の人物", "content": "過去の影、いまだ徘徊す。"},
    ],
  ),
  Stage(
    id: 32,
    name: '7-3 命運の回廊',
    recLevel: 54000,
    bg: 'maze',
    drops: ['Fate Thread'],
    story: [
      {"speaker": "時間法師", "content": "命運、それは書き換え得るものなり。"},
    ],
  ),
  Stage(
    id: 33,
    name: '7-4 時光の聖殿',
    recLevel: 61000,
    bg: 'temple',
    drops: ['Hourglass Shard'],
    story: [
      {"speaker": "ミカエル", "content": "時間よ、どうか私たちのために停止せよ！"},
    ],
  ),
  Stage(
    id: 34,
    name: '7-5 時空の主宰',
    recLevel: 69000,
    bg: 'void',
    drops: ['Chronos Core'],
    story: [
      {"speaker": "時空領主", "content": "時間の前には、全ては無なり！"},
    ],
  ),
  // ========== 第八章：魔界の辺境 ==========
  Stage(
    id: 35,
    name: '8-1 魔界の門',
    recLevel: 78000,
    bg: 'gate',
    drops: ['Demon Shard'],
    story: [
      {"speaker": "リリス", "content": "帰郷の感覚、これこそ。"},
    ],
  ),
  Stage(
    id: 36,
    name: '8-2 悪魔の城',
    recLevel: 87000,
    bg: 'castle',
    drops: ['Demon Horn'],
    story: [
      {"speaker": "影", "content": "ここの闇、私に親しみを感じさせる。"},
    ],
  ),
  Stage(
    id: 37,
    name: '8-3 煉獄の火山',
    recLevel: 97000,
    bg: 'lava',
    drops: ['Hell Flame'],
    story: [
      {"speaker": "フレイヤ", "content": "この炎、まだ熾烈たり得ず！"},
    ],
  ),
  Stage(
    id: 38,
    name: '8-4 魔王の大殿',
    recLevel: 108000,
    bg: 'palace',
    drops: ['Royal Seal'],
    story: [
      {"speaker": "リリス", "content": "かつての私、ここに坐せり。"},
    ],
  ),
  Stage(
    id: 39,
    name: '8-5 魔神降臨',
    recLevel: 120000,
    bg: 'altar',
    drops: ['God Fragment'],
    story: [
      {"speaker": "魔神", "content": "凡人よ、真なる絶望を味わうべし！"},
    ],
  ),
  // ========== 第九章：精霊の森 ==========
  Stage(
    id: 40,
    name: '9-1 翡翠の森林',
    recLevel: 135000,
    bg: 'forest',
    drops: ['Emerald Leaf'],
    story: [
      {"speaker": "ナレーター", "content": "古老の森林、生命の息遣い。"},
    ],
  ),
  Stage(
    id: 41,
    name: '9-2 生命の泉',
    recLevel: 150000,
    bg: 'spring',
    drops: ['Life Water'],
    story: [
      {"speaker": "エリン", "content": "これぞ大自然の恩賜なり。"},
    ],
  ),
  Stage(
    id: 42,
    name: '9-3 古樹の根',
    recLevel: 168000,
    bg: 'tree',
    drops: ['World Tree Bark'],
    story: [
      {"speaker": "蒼刃", "content": "千年の古樹、余りに多くを見届けたり。"},
    ],
  ),
  Stage(
    id: 43,
    name: '9-4 精霊王の宮廷',
    recLevel: 188000,
    bg: 'palace',
    drops: ['Royal Gem'],
    story: [
      {"speaker": "精霊女王", "content": "ようこそ、遠方より来たりし客人よ。"},
    ],
  ),
  Stage(
    id: 44,
    name: '9-5 世界樹',
    recLevel: 210000,
    bg: 'sky',
    drops: ['Yggdrasil Leaf'],
    story: [
      {"speaker": "世界樹の霊", "content": "生命の輪廻、永らく停むべからず。"},
    ],
  ),
  // ========== 第十章：竜の巣 ==========
  Stage(
    id: 45,
    name: '10-1 竜骨の荒原',
    recLevel: 235000,
    bg: 'wasteland',
    drops: ['Dragon Bone'],
    story: [
      {"speaker": "ナレーター", "content": "巨竜の墓場、悲歌が響き渡る。"},
    ],
  ),
  Stage(
    id: 46,
    name: '10-2 竜穴の入口',
    recLevel: 265000,
    bg: 'cave',
    drops: ['Dragon Scale'],
    story: [
      {"speaker": "フレイヤ", "content": "竜の息遣い、非常に強き力なり。"},
    ],
  ),
  Stage(
    id: 47,
    name: '10-3 竜族の宝庫',
    recLevel: 300000,
    bg: 'treasury',
    drops: ['Ancient Coin'],
    story: [
      {"speaker": "影", "content": "これほど多くの財宝…実に誘惑なり。"},
    ],
  ),
  Stage(
    id: 48,
    name: '10-4 竜王の神殿',
    recLevel: 340000,
    bg: 'temple',
    drops: ['Dragon Crown'],
    story: [
      {"speaker": "竜王", "content": "竜族の威厳、挑むを許さず！"},
    ],
  ),
  Stage(
    id: 49,
    name: '10-5 遠古の巨竜',
    recLevel: 385000,
    bg: 'altar',
    drops: ['Primordial Essence'],
    story: [
      {"speaker": "遠古の巨竜", "content": "我は創世の初めより、既に在りき！"},
    ],
  ),
  // ========== 第十一章：星界 ==========
  Stage(
    id: 50,
    name: '11-1 星河の渡口',
    recLevel: 435000,
    bg: 'space',
    drops: ['Star Fragment'],
    story: [
      {"speaker": "ナレーター", "content": "星河を跨越し、真実を追い求める。"},
    ],
  ),
  Stage(
    id: 51,
    name: '11-2 月の神殿',
    recLevel: 490000,
    bg: 'temple',
    drops: ['Moon Stone'],
    story: [
      {"speaker": "月の祭司", "content": "月光、あなたの道筋を照らさん。"},
    ],
  ),
  Stage(
    id: 52,
    name: '11-3 太陽の玉座',
    recLevel: 555000,
    bg: 'throne',
    drops: ['Sun Core'],
    story: [
      {"speaker": "太陽王", "content": "光明と熾熱、これ我が権能なり！"},
    ],
  ),
  Stage(
    id: 53,
    name: '11-4 星辰の玉座',
    recLevel: 630000,
    bg: 'throne',
    drops: ['Cosmic Shard'],
    story: [
      {"speaker": "星辰の主", "content": "億万の星辰、全て駒なり。"},
    ],
  ),
  Stage(
    id: 54,
    name: '11-5 宇宙の意志',
    recLevel: 720000,
    bg: 'void',
    drops: ['Universal Core'],
    story: [
      {"speaker": "？？？", "content": "一界の旅、それは始まりに過ぎず…"},
    ],
  ),
];
