import 'package:flutter/material.dart';

const List<String> beastNames = [
  "驳",
  "旋龟",
  "赤鱬",
  "九尾狐",
  "陆吾",
  "狰",
  "蛊雕",
  "毕方",
  "饕餮",
  "穷奇",
  "梼杌",
  "混沌",
  "应龙",
  "烛龙",
  "刑天",
  "夔牛",
  "相柳",
  "朱厌",
  "精卫",
  "鲲鹏",
  "白泽",
  "麒麟",
  "貔貅",
  "狻猊",
  "霸下",
  "狴犴",
  "赑屃",
  "螭吻",
  "蒲牢",
  "睚眦",
  "青龙",
  "白虎",
  "朱雀",
  "玄武",
  "帝江",
  "重明鸟",
  "英招",
  "夫诸",
  "当康",
  "祸斗",
  "鬼车",
];

const List<String> beastAdjectives = [
  "狂暴的",
  "虚弱的",
  "变异的",
  "远古的",
  "圣洁的",
  "魔化的",
  "幽冥的",
  "金刚的",
  "幻影的",
  "嗜血的",
  "雷霆的",
  "寂灭的",
  "涅槃的",
  "混沌的",
  "不朽的",
];

const List<String> beastParts = [
  "虎爪",
  "九尾",
  "马身",
  "独角",
  "蛇尾",
  "凤翼",
  "龟背",
  "人面",
  "鸟首",
  "龙鳞",
  "牛头",
  "鹿角",
  "鱼鳍",
  "鹰眼",
  "狼耳",
  "豹纹",
  "熊掌",
  "象鼻",
  "猿臂",
  "鹤足",
  "鳞甲",
  "羽翼",
  "触手",
  "尖牙",
  "铁骨",
  "寒冰",
  "烈焰",
  "雷霆",
  "剧毒",
  "魔瞳",
  "骨刺",
  "神纹",
  "光环",
];

const List<Map<String, dynamic>> initialBeasts = [
  {
    "id": "1",
    "name": "驳",
    "tier": "百年",
    "parts": ["马身", "虎爪", "独角"],
    "stats": {"hp": 120, "atk": 45, "def": 30, "spd": 25},
  },
  {
    "id": "2",
    "name": "九尾狐",
    "tier": "千年",
    "parts": ["狐身", "九尾", "人音"],
    "stats": {"hp": 350, "atk": 85, "def": 40, "spd": 60},
  },
  {
    "id": "3",
    "name": "陆吾",
    "tier": "万年",
    "parts": ["虎身", "九尾", "人面"],
    "stats": {"hp": 380, "atk": 70, "def": 55, "spd": 45},
  },
];

// 扩展后的征伐关卡 - 增加了过渡关卡和终局挑战
const List<Map<String, dynamic>> dungeons = [
  {
    "id": "1",
    "name": "雷泽 · 外围",
    "desc": "雷霆初生之地，异兽多躁动不安。",
    "level": "凡境",
    "power": 1200,
    "boss": "雷泽兽王",
    "drop": ["灵气", "百年兽蛋"],
    "gradient": ["0xFF1E293B", "0xFF134E4A"], // Slate 800 -> Teal 900
    "status": "unlocked",
    "minTribeLevel": 1,
  },
  {
    "id": "2",
    "name": "青丘 · 狐岐",
    "desc": "十里桃林，暗藏杀机，魅影重重。",
    "level": "灵境",
    "power": 3500,
    "boss": "六尾魔狐",
    "drop": ["灵狐毛", "魅惑之瞳"],
    "gradient": ["0xFF1E293B", "0xFFBE185D"], // Slate 800 -> Pink 700
    "status": "unlocked",
    "minTribeLevel": 2,
  },
  {
    "id": "3",
    "name": "瀛洲 · 迷雾",
    "desc": "海外仙山，终年云雾缭绕，难辨虚实。",
    "level": "灵境·破",
    "power": 5200,
    "boss": "迷雾蜃龙",
    "drop": ["蜃气珠", "幻境碎片"],
    "gradient": ["0xFF334155", "0xFF64748B"], // Slate 700 -> Slate 500
    "status": "unlocked",
    "minTribeLevel": 3,
  },
  {
    "id": "4",
    "name": "昆仑 · 虚空",
    "desc": "万山之祖，虚空裂缝中有古神低语。",
    "level": "玄境",
    "power": 6800,
    "boss": "虚空之主",
    "drop": ["千年兽骨", "虚空结晶"],
    "gradient": ["0xFF1E293B", "0xFF581C87"], // Slate 800 -> Purple 900
    "status": "locked",
    "minTribeLevel": 5,
  },
  {
    "id": "5",
    "name": "弱水 · 深渊",
    "desc": "鸿毛不浮，飞鸟难过，深渊之下有大恐怖。",
    "level": "玄境·极",
    "power": 9500,
    "boss": "弱水之灵",
    "drop": ["重水精", "深渊之眼"],
    "gradient": ["0xFF020617", "0xFF172554"], // Slate 950 -> Blue 950
    "status": "locked",
  },
  {
    "id": "6",
    "name": "幽都 · 黄泉",
    "desc": "生人勿进，亡者徘徊，阴气森森。",
    "level": "地境",
    "power": 12000,
    "boss": "黄泉鬼将",
    "drop": ["彼岸花", "幽冥鬼火"],
    "gradient": ["0xFF020617", "0xFF312E81"], // Slate 950 -> Indigo 900
    "status": "locked",
  },
  {
    "id": "7",
    "name": "扶桑 · 神木",
    "desc": "日出之处，神木参天，烈焰焚尽万物。",
    "level": "地境·炎",
    "power": 18000,
    "boss": "三足金乌",
    "drop": ["太阳真火", "扶桑枝"],
    "gradient": ["0xFF450A0A", "0xFFF59E0B"], // Red 950 -> Amber 500
    "status": "locked",
  },
  {
    "id": "8",
    "name": "不周山 · 遗迹",
    "desc": "天柱折断之处，残留着上古战意。",
    "level": "天境",
    "power": 25000,
    "boss": "刑天残魂",
    "drop": ["万年神魂", "战神之斧"],
    "gradient": ["0xFF1E293B", "0xFF881337"], // Slate 800 -> Rose 900
    "status": "locked",
  },
  {
    "id": "9",
    "name": "北海 · 极寒",
    "desc": "穷发之北，天池之水，鲲鹏展翅九万里。",
    "level": "天境·巅",
    "power": 36000,
    "boss": "鲲鹏祖师",
    "drop": ["北冥寒气", "逍遥游"],
    "gradient": ["0xFF0C4A6E", "0xFF0EA5E9"], // Sky 900 -> Sky 500
    "status": "locked",
  },
  {
    "id": "10",
    "name": "天穹 · 破碎",
    "desc": "三十三天之上，直面天道审判。",
    "level": "神境",
    "power": 50000,
    "boss": "天道化身",
    "drop": ["补天石", "混沌本源"],
    "gradient": ["0xFF0F172A", "0xFFD97706"], // Slate 900 -> Amber 600
    "status": "locked",
  },
  {
    "id": "11",
    "name": "修罗 · 炼狱",
    "desc": "六道之外，杀伐之气凝聚成实质。",
    "level": "神境·杀",
    "power": 72000,
    "boss": "阿修罗王",
    "drop": ["修罗战意", "杀伐之剑"],
    "gradient": ["0xFF000000", "0xFFDC2626"], // Black -> Red 600
    "status": "locked",
  },
  {
    "id": "12",
    "name": "混沌 · 归墟",
    "desc": "万物终焉，一切归于虚无。",
    "level": "劫境",
    "power": 99999,
    "boss": "盘古残念",
    "drop": ["创世青莲", "开天斧气"],
    "gradient": ["0xFF000000", "0xFFFFFFFF"], // Black -> White
    "status": "locked",
  },
  {
    "id": "13",
    "name": "鸿蒙 · 太初",
    "desc": "天地未开，鸿蒙初判，大道之源。",
    "level": "圣境",
    "power": 150000,
    "boss": "大道法则",
    "drop": ["鸿蒙紫气", "造化玉碟"],
    "gradient": ["0xFF3B0764", "0xFFEAB308"], // Purple 950 -> Yellow 500
    "status": "locked",
  },
  {
    "id": "14",
    "name": "虚空 · 彼岸",
    "desc": "超越维度的存在，不可名状的大恐怖。",
    "level": "不可知",
    "power": 300000,
    "boss": "虚空主宰",
    "drop": ["代码之源", "回溯时光"],
    "gradient": ["0xFF000000", "0xFF475569"], // Black -> Slate 600
    "status": "locked",
  },
];

const List<Map<String, dynamic>> totems = [
  {
    "id": "1",
    "name": "蛮荒之力",
    "desc": "所有异兽攻击 +5%",
    "level": 3,
    "cost": 500,
    "icon": "swords",
  },
  {
    "id": "2",
    "name": "灵脉感知",
    "desc": "挂机灵气收益 +10%",
    "level": 5,
    "cost": 800,
    "icon": "zap",
  },
  {
    "id": "3",
    "name": "血肉吞噬",
    "desc": "吞噬成功率 +2%",
    "level": 1,
    "cost": 2000,
    "icon": "droplet",
  },
  {
    "id": "4",
    "name": "坚韧甲壳",
    "desc": "所有异兽防御 +5%",
    "level": 1,
    "cost": 1200,
    "icon": "shield", // Need to handle icon mapping in UI
  },
  {
    "id": "5",
    "name": "迅捷之风",
    "desc": "所有异兽速度 +5%",
    "level": 0,
    "cost": 1500,
    "icon": "wind",
  },
  {
    "id": "6",
    "name": "气运加身",
    "desc": "异变/完美融合概率 +1%",
    "level": 0,
    "cost": 3000,
    "icon": "stars",
  },
  {
    "id": "7",
    "name": "不死传说",
    "desc": "融合死亡概率 -1%",
    "level": 0,
    "cost": 5000,
    "icon": "heart",
  },
];

const List<Map<String, dynamic>> battleSkills = [
  {"name": "撕咬", "type": "physical", "color": "0xFF94A3B8"},
  {"name": "践踏", "type": "physical", "color": "0xFF94A3B8"},
  {"name": "雷击", "type": "magical", "color": "0xFFC084FC"},
  {"name": "毒雾", "type": "dot", "color": "0xFF34D399"},
  {"name": "业火", "type": "magical", "color": "0xFFFB7185"},
  {"name": "龙息", "type": "magical", "color": "0xFFEF4444"},
  {"name": "冰封", "type": "magical", "color": "0xFF3B82F6"},
  {"name": "暗影", "type": "magical", "color": "0xFF8B5CF6"},
  {"name": "圣光", "type": "magical", "color": "0xFFF59E0B"},
  {"name": "裂空", "type": "physical", "color": "0xFF64748B"},
  {"name": "缠绕", "type": "dot", "color": "0xFF22C55E"},
  {"name": "咆哮", "type": "physical", "color": "0xFFF97316"},
  {"name": "湮灭", "type": "magical", "color": "0xFF000000"},
  {"name": "神罚", "type": "physical", "color": "0xFFEAB308"},
  {"name": "轮回", "type": "magical", "color": "0xFFEC4899"},
  {"name": "吞天", "type": "physical", "color": "0xFF1E293B"},
];
