import '../Moodmodels/journal.dart';

class SampleDataService {
  static List<Journal> getSampleJournals() {
    // 创建5个不同的用户ID，让日记分布在不同用户下
    final users = ['user_001', 'user_002', 'user_003', 'user_004', 'user_005'];
    
    return [
      Journal(
        id: '1',
        title: '清晨的第一缕阳光',
        content: '今天早上看到窗台上的花儿开了，阳光正好洒在花瓣上，整个世界都变得温柔起来。新的一天开始了，希望能把这份美好留在心里。',
        imageUrl: 'assets/Riji_1.jpeg',
        emotionTags: ['peaceful', 'hope'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 2)),
        userId: users[0],
      ),
      Journal(
        id: '2',
        title: '深夜的思考',
        content: '又是一个失眠的夜晚，脑子里像过电影一样回想着今天发生的事。有些焦虑，但更多的是对明天的期待。明天会更好的，对吧？',
        imageUrl: 'assets/Riji_2.jpeg',
        emotionTags: ['anxiety', 'hope'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(hours: 5)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 5)),
        userId: users[1],
      ),
      Journal(
        id: '3',
        title: '项目完成的瞬间',
        content: '历经一个月的项目终于完成了！团队一起努力的感觉真的很棒，虽然累但很值得。深夜里看着代码，心中充满了成就感。',
        imageUrl: 'assets/Riji_3.jpeg',
        emotionTags: ['hope', 'joy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(hours: 8)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 8)),
        userId: users[2],
      ),
      Journal(
        id: '4',
        title: '山间的云朵',
        content: '今天的心情就像山间的云朵一样，变幻莫测。时而清晰时而迷茫，但总会有阳光穿透云层的那一刻。',
        imageUrl: 'assets/Riji_4.jpeg',
        emotionTags: ['peaceful', 'anxiety'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(hours: 12)),
        updatedAt: DateTime.now().subtract(const Duration(hours: 12)),
        userId: users[3],
      ),
      Journal(
        id: '5',
        title: '晨光熹微',
        content: '清晨的第一缕阳光总是能治愈夜晚的疲惫。新的一天，新的希望，我要好好珍惜每一个当下。',
        imageUrl: 'assets/Riji_5.jpeg',
        emotionTags: ['hope', 'joy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(days: 1, hours: 2)),
        userId: users[4],
      ),
      Journal(
        id: '6',
        title: '孤独与力量',
        content: '有时候，孤独也是一种力量。在这份宁静中，我听见了内心最真实的声音。',
        imageUrl: 'assets/Riji_6.jpeg',
        emotionTags: ['peaceful', 'tired'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 1, hours: 6)),
        userId: users[0],
      ),
      Journal(
        id: '7',
        title: '咖啡的香气',
        content: '午后的咖啡香总是能让人平静下来。一杯咖啡，一本书，这就是我想要的简单生活。',
        imageUrl: 'assets/Riji_7.jpeg',
        emotionTags: ['peaceful', 'joy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 1, hours: 12)),
        updatedAt: DateTime.now().subtract(const Duration(days: 1, hours: 12)),
        userId: users[1],
      ),
      Journal(
        id: '8',
        title: '雨后彩虹',
        content: '今天下了一场雨，雨停后竟然看到了彩虹。生活不也是这样吗？经历过风雨，总会遇见美好的风景。',
        imageUrl: 'assets/Riji_8.jpeg',
        emotionTags: ['hope', 'joy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
        updatedAt: DateTime.now().subtract(const Duration(days: 2, hours: 3)),
        userId: users[2],
      ),
      Journal(
        id: '9',
        title: '夜晚的城市',
        content: '城市的夜晚总是灯火通明，每一盏灯背后都有自己的故事。而我，只是其中一个微不足道却独特的存在。',
        imageUrl: 'assets/Riji_9.jpeg',
        emotionTags: ['peaceful', 'tired'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 2, hours: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 2, hours: 10)),
        userId: users[3],
      ),
      Journal(
        id: '10',
        title: '温暖的拥抱',
        content: '一个拥抱可以治愈很多很多。今天抱了抱妈妈，突然觉得什么困难都不怕了。家永远是最好的港湾。',
        imageUrl: 'assets/Riji_10.jpeg',
        emotionTags: ['love', 'peaceful'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 5)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3, hours: 5)),
        userId: users[4],
      ),
      Journal(
        id: '11',
        title: '疲惫的一天',
        content: '今天真的很累，但还是坚持完成了所有事情。有时候觉得自己就像超人一样，但其实我也需要休息。',
        imageUrl: 'assets/Riji_11.jpeg',
        emotionTags: ['tired', 'hope'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 3, hours: 15)),
        updatedAt: DateTime.now().subtract(const Duration(days: 3, hours: 15)),
        userId: users[0],
      ),
      Journal(
        id: '12',
        title: '窗外的风景',
        content: '坐在窗边发呆，看看云朵变换形状，听听鸟儿的歌声。有时候幸福就是这么简单。',
        imageUrl: 'assets/Riji_12.jpg',
        emotionTags: ['peaceful', 'grateful'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 4, hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4, hours: 2)),
        userId: users[1],
      ),
      Journal(
        id: '13',
        title: '朋友的笑声',
        content: '和朋友一起吃饭，聽到她爽朗的笑聲，感覺整個世界都亮了起來。友誼真的是世界上最珍貴的財富。',
        imageUrl: 'assets/Riji_13.jpg',
        emotionTags: ['joy', 'love'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 4, hours: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 4, hours: 8)),
        userId: users[2],
      ),
      Journal(
        id: '14',
        title: '内心的声音',
        content: '今天终于鼓起勇气去做了一直想做的事。虽然有些紧张，但内心深处的声音告诉我，这是对的。',
        imageUrl: 'assets/Riji_14.jpg',
        emotionTags: ['hope', 'energy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 5, hours: 3)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5, hours: 3)),
        userId: users[3],
      ),
      Journal(
        id: '15',
        title: '小小的惊喜',
        content: '路上看到一只小猫，毛茸茸的，一直跟着我走了好一段路。小小的惊喜让整个下午都变得美好。',
        imageUrl: 'assets/Riji_15.jpg',
        emotionTags: ['joy', 'peaceful'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 5, hours: 12)),
        updatedAt: DateTime.now().subtract(const Duration(days: 5, hours: 12)),
        userId: users[4],
      ),
      Journal(
        id: '16',
        title: '深夜电台',
        content: '深夜聽廣播，主持人的聲音很溫柔，說著那些關於青春和夢想的故事。仿佛又回到了那些美好的年歲。',
        imageUrl: 'assets/Riji_16.jpg',
        emotionTags: ['peaceful', 'hope'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 6, hours: 1)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6, hours: 1)),
        userId: users[0],
      ),
      Journal(
        id: '17',
        title: '努力的意义',
        content: '今天看到一句话："努力的意义不在于超越别人，而在于成为更好的自己。"深有感触，我会继续努力的。',
        imageUrl: 'assets/Riji_17.jpg',
        emotionTags: ['hope', 'energy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 6, hours: 10)),
        updatedAt: DateTime.now().subtract(const Duration(days: 6, hours: 10)),
        userId: users[1],
      ),
      Journal(
        id: '18',
        title: '书香时光',
        content: '在图书馆泡了一下午，翻阅著喜歡的書。时间过得很快，但内心很充实。知識的力量真的很神奇。',
        imageUrl: 'assets/Riji_18.jpg',
        emotionTags: ['peaceful', 'grateful'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 7, hours: 4)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7, hours: 4)),
        userId: users[2],
      ),
      Journal(
        id: '19',
        title: '久违的眼泪',
        content: '看了一部很感人的电影，眼泪止不住地流。有时候哭出来也是一种释放情感的方式。',
        imageUrl: 'assets/Riji_19.jpg',
        emotionTags: ['peaceful', 'grateful'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 7, hours: 14)),
        updatedAt: DateTime.now().subtract(const Duration(days: 7, hours: 14)),
        userId: users[3],
      ),
      Journal(
        id: '20',
        title: '感谢有你',
        content: '感谢生活中遇到的每一个人，每一件事。无论是快乐还是痛苦，都是成长路上最好的老师。',
        imageUrl: 'assets/Riji_20.jpg',
        emotionTags: ['grateful', 'love'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 8, hours: 2)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8, hours: 2)),
        userId: users[4],
      ),
      Journal(
        id: '21',
        title: '新的开始',
        content: '新的一个月开始了，给自己定下了一些小目标。希望每天都能进步一点点，成为更好的自己。',
        imageUrl: 'assets/Riji_21.jpg',
        emotionTags: ['hope', 'joy'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 8, hours: 8)),
        updatedAt: DateTime.now().subtract(const Duration(days: 8, hours: 8)),
        userId: users[0],
      ),
      Journal(
        id: '22',
        title: '温柔的月光',
        content: '今晚的月亮特别亮，洒在床边的月光像银色的丝绸。伴着月光入睡，应该会做个好梦吧。',
        imageUrl: 'assets/Riji_22.jpg',
        emotionTags: ['peaceful', 'hope'],
        isPrivate: false,
        createdAt: DateTime.now().subtract(const Duration(days: 9, hours: 6)),
        updatedAt: DateTime.now().subtract(const Duration(days: 9, hours: 6)),
        userId: users[1],
      ),
    ];
  }

  static Future<void> initializeSampleData() async {
    // This method can be used to populate initial data if needed
  }
}
